const ActionType = {
    GET_FEED_MESSAGES_REQUEST: "GET_FEED_MESSAGES_REQUEST",
    GET_FEED_MESSAGES_SUCCESS: "GET_FEED_MESSAGES_SUCCESS",
    GET_FEED_MESSAGES_FAILURE: "GET_FEED_MESSAGES_FAILURE"
};

export default ActionType;