const ActionType = {
    EVENT_SWIPE: "EVENT_SWIPE",
    EVENT_SHAKE: "EVENT_SHAKE",

    POSITION_MOVE: "POSITION_MOVE",

    GET_USER_BASIC_REQUEST: "GET_USER_BASIC_REQUEST",
    GET_USER_BASIC_SUCCESS: "GET_USER_BASIC_SUCCESS",
    GET_USER_BASIC_FAILURE: "GET_USER_BASIC_FAILURE",
    
    GET_USER_EXTENDED_REQUEST: "GET_USER_EXTENDED_REQUEST",
    GET_USER_EXTENDED_SUCCESS: "GET_USER_EXTENDED_SUCCESS",
    GET_USER_EXTENDED_FAILURE: "GET_USER_EXTENDED_FAILURE",
    
    GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
    GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
    GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
    
    GET_PROXIMATE_GAMES_REQUEST: "GET_PROXIMATE_GAMES_REQUEST",
    GET_PROXIMATE_GAMES_SUCCESS: "GET_PROXIMATE_GAMES_SUCCESS",
    GET_PROXIMATE_GAMES_FAILURE: "GET_PROXIMATE_GAMES_FAILURE"
}

export default ActionType;