const ActionType = {
    GET_FEED_MESSAGES_REQUEST: "GET_FEED_MESSAGES_REQUEST",
    GET_FEED_MESSAGES_SUCCESS: "GET_FEED_MESSAGES_SUCCESS",
	GET_FEED_MESSAGES_FAILURE: "GET_FEED_MESSAGES_FAILURE",
	
    POST_FEED_MESSAGE_REQUEST: "POST_FEED_MESSAGE_REQUEST",
    POST_FEED_MESSAGE_SUCCESS: "POST_FEED_MESSAGE_SUCCESS",
    POST_FEED_MESSAGE_FAILURE: "POST_FEED_MESSAGE_FAILURE"
};

export default ActionType;